function divergence_diff_summand = divergence_diff_summand_line_quad_code(t,a,b,c,f,g,h,inten_sym,alpha_sym,beta_sym,alpha_A,alpha_B,alpha_C,P,K)
%DIVERGENCE_DIFF_SUMMAND_LINE_QUAD_CODE
%    DIVERGENCE_DIFF_SUMMAND = DIVERGENCE_DIFF_SUMMAND_LINE_QUAD_CODE(T,A,B,C,F,G,H,INTEN_SYM,ALPHA_SYM,BETA_SYM,ALPHA_A,ALPHA_B,ALPHA_C,P,K)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    03-Aug-2012 15:43:04

t2 = g.*t;
t3 = b+t2;
t4 = h.*t;
t5 = c+t4;
t6 = t3.*t5;
t7 = t6+1.0;
t8 = 1.0./t7;
t9 = f.*t;
t10 = a+t9;
t11 = h.*t8.*t10;
t12 = f.*t5.*t8;
t13 = 1.0./t7.^2;
t14 = h.*t3;
t15 = g.*t5;
t16 = t14+t15;
t17 = t11+t12-t5.*t10.*t13.*t16;
t18 = t5.*t8.*t10;
t19 = 1.0./K;
divergence_diff_summand = (beta_sym.*t17.*t18.^(alpha_sym+beta_sym-1.0)-beta_sym.*inten_sym.^alpha_sym.*t17.*t18.^(beta_sym-1.0))./(alpha_sym.*beta_sym)+alpha_A.*f.*t19+alpha_B.*g.*t19+(alpha_C.*h)./P;
