syms t a b c f g h alpha_sym beta_sym inten_sym alpha_A alpha_B alpha_C P K;
langmuir_func_sym = symfun(sym('(a + t * f) * (c + t * h) / (1 + (b + t * g) * (c + t * h))'), [t a b c f g h]);
%divergence_summand = symfun(sym(strcat('-(1 / (alpha_sym * beta_sym)) * ', ...
%    '(inten_sym^alpha * langmuir_func_sym(t, a, b, c, f, g, h)^beta - (alpha_sym / (alpha_sym + beta_sym)) * inten_sym ^ (alpha_sym + beta_sym) - ', ...
%    '(beta_sym / (alpha_sym + beta_sym)) * langmuir_func_sym(t, a, b, c, f, g, h) ^ (alpha_sym + beta_sym))')), [t a b c f g h inten_sym alpha_sym beta_sym]);
divergence_summand = symfun(sym(strcat('-(1 / (alpha_sym * beta_sym)) * ', ...
   '(inten_sym^alpha_sym * ((a + t * f) * (c + t * h) / (1 + (b + t * g) * (c + t * h)))^beta_sym - (alpha_sym / (alpha_sym + beta_sym)) * inten_sym ^ (alpha_sym + beta_sym) - ', ...
   '(beta_sym / (alpha_sym + beta_sym)) * ((a + t * f) * (c + t * h) / (1 + (b + t * g) * (c + t * h))) ^ (alpha_sym + beta_sym)) + ', ...
   'alpha_A * (a + t * f) / K + alpha_B * (b + t * g) / K + alpha_C * (c + t * h) / P')), [t a b c f g h inten_sym alpha_sym beta_sym alpha_A alpha_B alpha_C P K]);
divergence_diff_summand = diff(divergence_summand, t);
matlabFunction(divergence_diff_summand, 'file', 'divergence_diff_summand_line_quad_code.m', ...
    'vars', {'t', 'a', 'b', 'c', 'f', 'g', 'h', 'inten_sym', 'alpha_sym', 'beta_sym', 'alpha_A', 'alpha_B', 'alpha_C', 'P', 'K'});
%matlabFunction(divergence_summand, 'file', 'divergence_summand_line_quad_code.m', 'vars', {'t', 'a', 'b', 'c', 'f', 'g', 'h', 'inten_sym', 'alpha_sym', 'beta_sym'});

%%
syms t a b c f g h alpha_sym beta_sym inten_sym alpha_reg;
divergence_summand = symfun(sym(strcat('-(1 / (alpha_sym * beta_sym)) * ', ...
   '(inten_sym^alpha_sym * ((a + t * f) * (c + t * h) / (1 + (b + t * g) * (c + t * h)))^beta_sym - (alpha_sym / (alpha_sym + beta_sym)) * inten_sym ^ (alpha_sym + beta_sym) - ', ...
   '(beta_sym / (alpha_sym + beta_sym)) * ((a + t * f) * (c + t * h) / (1 + (b + t * g) * (c + t * h))) ^ (alpha_sym + beta_sym)) + ', ...
   'alpha_reg * (1 + (b + t * g) * (c + t * h))^2 / (a + t * f)')), [t a b c f g h inten_sym alpha_sym beta_sym alpha_reg]);
divergence_diff_summand = diff(divergence_summand, t);
matlabFunction(divergence_diff_summand, 'file', 'divergence_diff_summand_line_regvoron_code.m', ...
    'vars', {'t', 'a', 'b', 'c', 'f', 'g', 'h', 'inten_sym', 'alpha_sym', 'beta_sym', 'alpha_reg'});
%matlabFunction(divergence_summand, 'file', 'divergence_summand_line_quad_code.m', 'vars', {'t', 'a', 'b', 'c', 'f', 'g', 'h', 'inten_sym', 'alpha_sym', 'beta_sym'});
